spring.config.activate.on-profile= prod
spring.application.name=${SPRING_APP_NAME:eazybankbackend}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:ERROR}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
# disable SQL Syntax Highlighting
spring.jpa.properties.hibernate.highlight_sql=${HIBERNATE_HIGHLIGHT_SQL:false}

server.servlet.session.timeout=${SESSION_TIMEOUT:10m}
